#!/usr/bin/env python3
#
import sys

import datetime

import base32_crockford
#from bases import Bases
#bases = Bases()


strdate = 0
if len(sys.argv) > 1:
    datelength=len(sys.argv[1])
    if datelength == 12:
        longdate=str(sys.argv[1])
        strdate=longdate[2:]
    elif datelength == 10: 
        strdate=sys.argv[1]
    else:
        sys.stdout.write("Err: wrong format")
        sys.stdout.write(str(datelength))
        exit
else:
    now = datetime.datetime.now()
    strdate = now.strftime("%y%m%d%H%M")

#print(str(bases.toBase32(int(strdate))).lower())
#sys.stdout.write(str(strdate))
sys.stdout.write(str(base32_crockford.encode(int(strdate))).lower())

