#!/bin/bash

# Calculates a simple hash

USAGE='<-l length> <string> [<Password>]'


arg=$1

die () { echo $@; exit 1; }

Length= String= Password=
if [ "$arg" = '-l' ] ; then
  Length=$2
  String=$3
  Password=$4
else
   String=$1
   Password=$2
fi

[ -n "$String" ] || die "usage: $USAGE" 

if [ -z "$Password" ] ; then
  echo "Please: enter password"
   read -s Password
 fi

if [ -n "$Length" ] ; then
   printf "${Password}${String}" | shasum | xxd -r -p | base64 | cut -c1-${Length}
else
   printf "${Password}${String}" | shasum | xxd -r -p | base64 
fi
