" Specify a directory for plugins (for Neovim: ~/.local/share/nvim/plugged)
"call plug#begin('~/.vim/plugged')
"Plug 'https://github.com/Alok/notational-fzf-vim'
"Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
" Initialize plugin system
"call plug#end()
"
set shell=/bin/sh

let mapleader=","
let maplocalleader=","

set modelines=1

set nu
set noerrorbells
set vb t_vb=


set nocompatible
behave xterm
filetype plugin indent on
syntax on

if !empty(glob(expand("~/.vim/bundle")))
   execute pathogen#infect()

	"au VimEnter * RainbowParenthesesToggle
	"au Syntax * RainbowParenthesesLoadRound
	"au Syntax * RainbowParenthesesLoadSquare
	"au Syntax * RainbowParenthesesLoadBraces
endif



for fpath in split(globpath('~/.vimrc.d/', '*.vim'), '\n')
  exe 'source' fpath
endfor

if has("gui_running")
syntax on
	set hlsearch
	colorscheme slate
	set	guifont=Monaco:h15
	set bs=2
	set ai
	set ruler
endif

set laststatus=2

au VimEnter * syntax keyword Statement lambda conceal cchar=λ
au VimEnter * hi! link Conceal Statement
au VimEnter * set conceallevel=2
set ruler


" Faster buffer switch
nnoremap <Leader>b :ls<CR>:b<Space>


syntax enable
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab

au BufReadPost *.w set syntax=perl
autocmd BufReadPost *.org call OrgModeHi('perl', 'perl')
autocmd BufReadPost *.org call OrgModeHi('bash', 'sh')
autocmd BufReadPost *.org call OrgModeHi('emacs-lisp', 'lisp')

syn region JakeTitle start="<<" end=">>"
highlight JakeTitle ctermbg=black ctermfg=yellow



" gui colors
set background=dark
hi SpecialKey guifg=Blue
hi MoreMsg guifg=Green
hi Visual guifg=NONE guibg=NONE
hi Folded ctermbg=4 guibg=Blue
hi FoldColumn ctermbg=7
hi DiffAdd guibg=Blue
hi DiffChange guibg=Magenta
hi DiffDelete guibg=Cyan
hi Normal guifg=Gray guibg=Black
hi Cursor guibg=White
hi lCursor guibg=White
hi Comment guifg=Cyan
hi Constant guifg=Magenta
hi Special guifg=Red
hi Identifier guifg=Cyan
hi Statement guifg=Yellow
hi PreProc guifg=Blue
hi Type guifg=Green
hi Underlined guifg=Blue
hi Todo guifg=Black
